import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import Footer from '@/components/Footer';

const inter = Inter({
    subsets: ['cyrillic', 'latin']
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html className={inter.className} suppressHydrationWarning>
            <body className="bg-lime-50">
                <nav className='sticky top-0 z-50 mb-10'>
                    <Navbar />
                </nav>
                <div className="mx-auto max-w-7xl grid grid-cols-1 gap-5 md:grid-cols-3">
                    <main className="col-span-2">
                        {children}
                    </main>
                    <aside className="border-l border-lime-300 pl-5">
                        <Sidebar />
                    </aside>
                </div>
                <footer className="mx-auto max-w-5xl my-10 pt-5 border-t border-lime-950 text-center">
                    <Footer />
                </footer>
            </body>
        </html>
    );
}
