export default function Home() {
    return (
        <article className="text-justify">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus in magna et sagittis. Quisque iaculis purus dolor, sed faucibus arcu pulvinar ut. Aenean mollis blandit neque, blandit placerat felis pharetra ac. Fusce eget rutrum ante, a congue lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim orci nunc, eget viverra arcu hendrerit a. In eget ullamcorper dui, eu consequat dolor. Quisque molestie cursus porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id mattis mauris. In quis leo orci. Aenean et velit arcu. Pellentesque tincidunt eget elit cursus pharetra. Cras cursus luctus leo sed fermentum. Nam iaculis rhoncus elit, nec cursus purus. Duis sit amet mauris quis justo sagittis dignissim non a nulla.

Vestibulum vel massa in turpis congue vulputate sit amet sit amet sapien. Cras elementum nisi nec tristique consectetur. Nulla eu sem odio. Duis lobortis et nulla sed aliquam. Duis sollicitudin nec lorem id congue. Praesent rutrum, diam eu elementum consectetur, felis eros convallis tortor, vel tincidunt augue massa eleifend turpis. In consectetur lacinia turpis. Pellentesque vitae lorem at lacus consequat finibus nec a justo. Aenean lacinia erat nibh, a fringilla odio porta non. Nunc quis pellentesque lacus. Duis quis metus pretium, tincidunt urna nec, porta tortor. Nulla ut sollicitudin nisi. Etiam sed auctor mi.

Aliquam eleifend sem sem, non efficitur velit lacinia quis. Donec euismod eget sem ut lobortis. Donec congue sapien a nunc hendrerit malesuada. Aliquam placerat tellus non sapien malesuada mollis a sed mi. Etiam porta tellus sed ex pellentesque euismod. Nam sit amet odio consequat, gravida ante ac, finibus neque. Curabitur dignissim tellus ipsum, id tristique risus facilisis id. Curabitur porttitor tortor at orci porta, et eleifend felis tincidunt. Aenean molestie porta felis, id laoreet mauris suscipit vel. Etiam non cursus tortor, in iaculis neque. Nam metus orci, posuere et metus sed, faucibus convallis velit.

Ut placerat imperdiet ornare. Phasellus eget ipsum at arcu facilisis egestas vel a dolor. Nam dignissim sollicitudin imperdiet. Etiam ut ullamcorper turpis. Etiam nec mauris porta, pretium ipsum at, fermentum massa. Etiam porttitor, orci quis tincidunt bibendum, enim est posuere ipsum, eget pretium sapien ex commodo tellus. Praesent at fringilla lacus. Nam dolor sapien, consectetur eget nibh ac, consectetur porttitor ligula. Nullam non sapien eu est vestibulum sollicitudin nec non magna. Fusce molestie ultrices ipsum, id finibus leo vestibulum vel. Aliquam fermentum posuere pharetra. Suspendisse elementum iaculis leo, non consequat sapien interdum sed.

Nulla placerat sem justo, non sollicitudin justo aliquet ac. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque ac tortor et nulla tincidunt bibendum. Fusce nec dictum neque. Nunc eu purus faucibus tortor molestie porta eget at ex. Aenean a consectetur libero. Donec rhoncus felis et magna gravida tincidunt. Sed erat nisi, finibus a metus molestie, aliquet iaculis turpis. Suspendisse ac pretium urna. Pellentesque ornare sapien quis erat cursus pharetra.

Vestibulum maximus diam non diam volutpat accumsan. Phasellus vehicula feugiat pulvinar. Sed mattis elit eget tellus maximus convallis. Etiam blandit lacus leo, sit amet venenatis elit aliquam ac. Fusce erat orci, maximus sagittis pellentesque at, condimentum at nisi. Aenean eget porta nisl. Ut sem diam, pharetra vitae accumsan quis, cursus nec quam. Suspendisse auctor, mauris a eleifend dignissim, velit erat iaculis lectus, sit amet iaculis sem sem vitae erat.

Suspendisse feugiat vestibulum ultricies. Cras ac dignissim ipsum. Integer maximus sagittis nunc, nec pharetra lacus venenatis a. Donec at rhoncus est. Vivamus sagittis lectus eu metus ultrices hendrerit. Maecenas auctor tempor mattis. Curabitur at diam id ex feugiat faucibus vel eget tellus. Maecenas eget finibus libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut at sagittis mi, sed vestibulum libero. Nunc convallis sagittis est, sagittis feugiat turpis bibendum eget. Maecenas eu tortor sagittis, laoreet massa eu, vehicula nibh. Donec dictum accumsan metus, id sodales diam aliquam eget. Nullam maximus leo nec sapien eleifend dictum.

Cras ut pulvinar quam. Ut faucibus quam non ultrices rhoncus. Nunc dapibus lacus non consectetur vulputate. Nam eget aliquam est. Nunc ultrices pellentesque pellentesque. Vivamus elementum dignissim lorem, vitae convallis ante. Proin molestie consequat neque, sed tempus quam pretium id. Curabitur iaculis diam non lectus pulvinar, at semper nibh ullamcorper. Ut dolor ligula, tincidunt et magna imperdiet, dignissim consequat elit. Nullam in mauris id diam volutpat ornare eget et dui.

Sed ante diam, tincidunt nec sapien sed, hendrerit eleifend enim. Etiam vulputate volutpat luctus. Donec ac pretium lacus, et pharetra neque. Donec a fermentum diam. Proin ut tellus at risus pharetra maximus vel in purus. Sed imperdiet, mi vitae venenatis imperdiet, lectus risus accumsan enim, maximus molestie magna lacus et turpis. Nullam a est quis tortor vehicula egestas sed vitae lectus. Ut auctor hendrerit sollicitudin. In hac habitasse platea dictumst. Fusce nibh urna, malesuada at ante tempor, fermentum posuere felis.

In orci leo, molestie consequat purus commodo, vehicula posuere arcu. Vestibulum non leo et quam luctus consequat nec non tellus. Nam eu ipsum commodo, dictum nunc nec, pharetra nisi. Phasellus a blandit nisi, vitae consequat neque. Praesent mattis tortor et hendrerit iaculis. Nam egestas mauris elementum ante sollicitudin, aliquam egestas nunc blandit. Fusce viverra arcu enim, eu rhoncus est volutpat vel. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ac erat euismod massa viverra mollis sed at dui. Etiam aliquet urna nunc, sit amet scelerisque ante facilisis a. In vel tempor dui, in condimentum nibh. Praesent sit amet facilisis ex, in molestie orci. Morbi a rhoncus erat, tempus pulvinar neque. Nam vel massa diam. Nunc faucibus at massa ac varius.
        </article>
    );
}
